defaults:
  install_options: --no-ri --no-rdoc
gems:
- name: rails
  version: 2.3.5
- name: saucelabs-adapter
  version: >= 0
  check_for_upgrade: true
- name: selenium-client
  version: 1.2.18
- name: webrat
  version: 0.6.0
- name: sqlite3-ruby
- name: json
- name: rspec
  version: 1.3.0
- name: rspec-rails
  version: 1.3.2
